org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Kotlin JVM Target
kotlin.jvm.target=21
kotlin.jvm.target.validation.mode=IGNORE

# Android
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
